// export const data = {
//   products: [
//     {
//       id: "1",
//       name: "Pink Polo Shirt",
//       image: "/images/p1.jpg",
//       price: 120,
//       countInStock: 10,
//       rating: 4.5,
//       numReviews: 10,
//       description: "high quality shirt",
//     },
//     {
//       id: "2",
//       name: "Marl Polo Shirt",
//       image: "/images/p2.jpg",
//       price: 250,
//       countInStock: 0,
//       rating: 4.0,
//       numReviews: 10,
//       description: "high quality product",
//     },
//     {
//       id: "3",
//       name: "Slim Fit Polo Shirt",
//       image: "/images/p3.jpg",
//       price: 25,
//       countInStock: 15,
//       rating: 4.5,
//       numReviews: 14,
//       description: "high quality product",
//     },
//     {
//       id: "4",
//       name: "Orange Polo Shirt",
//       image: "/images/p4.jpg",
//       price: 65,
//       countInStock: 5,
//       rating: 4.5,
//       numReviews: 10,
//       description: "high quality product",
//     },
//   ],
// };

export const data = {
  products: [
    {
      id: "m_bqk33ad0h",
      createdAt: "2021-08-26T16:13:51.470Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 8,
      merchantId: "b_9vbdnv0r1",
      name: "Cucumber Salad",
      description: "Sesame vinaigrette dressing. Hot and spicy.",
      price: "7",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_oai1shawy-1630625071224",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 9,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 19,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_yli193wkh",
      createdAt: "2021-08-26T16:14:34.927Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 6,
      merchantId: "b_9vbdnv0r1",
      name: "Garden Salad",
      description: "Served with ginger dressing.",
      price: "7",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_zmldek2uw-1629994468849",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 9,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 24,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_ekuse86zb",
      createdAt: "2021-09-17T20:53:09.907Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 7,
      merchantId: "b_9vbdnv0r1",
      name: "Miso Soup",
      description: "",
      price: "4",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_ao5rz8vxi-1631914609944",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 3,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 42,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_i98pps0rj",
      createdAt: "2021-08-26T07:42:54.291Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 13,
      merchantId: "b_9vbdnv0r1",
      name: "Spicy Garlic Soy Edamame",
      description: "",
      price: "6.00",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_cmhir49j9-1629963769789",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 4,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 67,
      ingredientTags: null,
      badges: null,
      rating: {
        rating: {
          taste: 5,
          value: 5,
          overall: 3,
          portion: 0,
        },
        ratingSum: {
          taste: 5,
          value: 5,
          overall: 3,
          portion: 0,
        },
        reviewCount: 1,
      },
      ranking: 0,
      unitsSold: 9,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_66w4sjpp9",
      createdAt: "2021-09-17T21:06:27.402Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Sushi Deluxe Dinner",
      description:
        "Nice pieces of sushi (three salmon, two tuna, two yellowtail and two albacore) and one spicy tuna roll. Served with Miso soup & house salad.",
      price: "29",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_on9z565h9-1631914401305",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 70,
      categoryId: 34,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 75,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_fp46rg5hh",
      createdAt: "2021-09-17T20:53:10.190Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 4,
      merchantId: "b_9vbdnv0r1",
      name: "Braised String Beans",
      description: "",
      price: "12",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_6fsodldlz-1631914668812",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 41,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 10,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_k2ovotncy",
      createdAt: "2021-09-17T20:53:09.679Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 4,
      merchantId: "b_9vbdnv0r1",
      name: "Brown Rice",
      description: "",
      price: "2",
      photos: null,
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 35,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 11,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_cffayyqjk",
      createdAt: "2021-09-17T20:53:09.381Z",
      updatedAt: "2022-09-01T08:32:34.250Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Black Pepper Beef Mignon",
      description:
        "Chunks of tender beef wok-tossed with onions in a rich roasted black pepper sauce. Hot and spicy.",
      price: "22",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_wl3hrqnd5-1631914541358",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 40,
      categoryId: 36,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 5,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
  ],
};
