export const data = {
  products: [
    {
      id: "m_bqk33ad0h",
      createdAt: "2021-08-26T16:13:51.470Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 8,
      merchantId: "b_9vbdnv0r1",
      name: "Cucumber Salad",
      description: "Sesame vinaigrette dressing. Hot and spicy.",
      price: "7",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_oai1shawy-1630625071224",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 9,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 19,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_yli193wkh",
      createdAt: "2021-08-26T16:14:34.927Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 6,
      merchantId: "b_9vbdnv0r1",
      name: "Garden Salad",
      description: "Served with ginger dressing.",
      price: "7",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_zmldek2uw-1629994468849",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 9,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 24,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_ekuse86zb",
      createdAt: "2021-09-17T20:53:09.907Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 7,
      merchantId: "b_9vbdnv0r1",
      name: "Miso Soup",
      description: "",
      price: "4",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_ao5rz8vxi-1631914609944",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 3,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 42,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_i98pps0rj",
      createdAt: "2021-08-26T07:42:54.291Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 13,
      merchantId: "b_9vbdnv0r1",
      name: "Spicy Garlic Soy Edamame",
      description: "",
      price: "6.00",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_cmhir49j9-1629963769789",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 4,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 67,
      ingredientTags: null,
      badges: null,
      rating: {
        rating: {
          taste: 5,
          value: 5,
          overall: 3,
          portion: 0,
        },
        ratingSum: {
          taste: 5,
          value: 5,
          overall: 3,
          portion: 0,
        },
        reviewCount: 1,
      },
      ranking: 0,
      unitsSold: 9,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_66w4sjpp9",
      createdAt: "2021-09-17T21:06:27.402Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Sushi Deluxe Dinner",
      description:
        "Nice pieces of sushi (three salmon, two tuna, two yellowtail and two albacore) and one spicy tuna roll. Served with Miso soup & house salad.",
      price: "29",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_on9z565h9-1631914401305",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 70,
      categoryId: 34,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 75,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_fp46rg5hh",
      createdAt: "2021-09-17T20:53:10.190Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 4,
      merchantId: "b_9vbdnv0r1",
      name: "Braised String Beans",
      description: "",
      price: "12",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_6fsodldlz-1631914668812",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 41,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 10,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_k2ovotncy",
      createdAt: "2021-09-17T20:53:09.679Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 4,
      merchantId: "b_9vbdnv0r1",
      name: "Brown Rice",
      description: "",
      price: "2",
      photos: null,
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 35,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 11,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_cffayyqjk",
      createdAt: "2021-09-17T20:53:09.381Z",
      updatedAt: "2022-09-01T08:32:34.250Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Black Pepper Beef Mignon",
      description:
        "Chunks of tender beef wok-tossed with onions in a rich roasted black pepper sauce. Hot and spicy.",
      price: "22",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_wl3hrqnd5-1631914541358",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 40,
      categoryId: 36,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 5,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_y5e4jxtmd",
      createdAt: "2021-09-17T20:53:10.977Z",
      updatedAt: "2022-09-01T08:32:34.250Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Albacore",
      description: "Two pieces.",
      price: "6",
      photos: null,
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 62,
      categoryId: 32,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 2,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_xuoq5wr03",
      createdAt: "2021-09-17T21:06:25.635Z",
      updatedAt: "2022-09-01T08:32:34.250Z",
      version: 3,
      merchantId: "b_9vbdnv0r1",
      name: "Beef with Broccoli",
      description:
        "Tender beef, ginger, and green onions wok-tossed with soy sauce.",
      price: "18",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_wln2qedeo-1631915083921",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 50,
      categoryId: 36,
      inventory: {
        dailyCurrentStock: 0,
      },
      pointsToRedeem: null,
      displayOrder: 4,
      ingredientTags: {},
      badges: {},
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "hour",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_lpelpb8ok",
      createdAt: "2021-09-17T20:53:09.501Z",
      updatedAt: "2022-09-01T08:32:34.250Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Black Pepper Chicken",
      description:
        "Marinated tender chicken leg meat topped with black pepper sauce.",
      price: "18",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_e3nw8mzdc-1631914856771",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 65,
      categoryId: 36,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 6,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_1mjw80xgl",
      createdAt: "2021-09-17T21:06:25.869Z",
      updatedAt: "2022-09-01T08:32:34.250Z",
      version: 2,
      merchantId: "b_9vbdnv0r1",
      name: "Beef Fried Rice",
      description:
        "All fried rice entrée come with peas, carrots, scallions, & eggs.",
      price: "17",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_47uxftppk-1631914211048",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 42,
      categoryId: 35,
      inventory: {
        dailyCurrentStock: 0,
      },
      pointsToRedeem: null,
      displayOrder: 9,
      ingredientTags: {},
      badges: {},
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "hour",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_fav4q2zu3",
      createdAt: "2021-09-17T21:06:25.936Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 4,
      merchantId: "b_9vbdnv0r1",
      name: "Chicken Fried Rice",
      description:
        "All fried rice entrée come with peas, carrots, scallions, & eggs.",
      price: "15",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_7gvams1yx-1631914625608",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 49,
      categoryId: 35,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 13,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_2johwfbcz",
      createdAt: "2021-09-17T20:53:11.103Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Manila Clams",
      description: "Black bean sauce and jalapenos. Hot and spicy.",
      price: "18",
      photos: null,
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 39,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 40,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_hqzd31vc8",
      createdAt: "2021-09-17T21:06:25.997Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Crab meat Fried Rice",
      description:
        "Snow crab, cucumber and egg whites. All fried rice entrée come with peas, carrots, scallions, & eggs.",
      price: "17",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_ofc36lote-1631914755490",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 35,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 15,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_6djiufomu",
      createdAt: "2021-09-17T21:06:26.163Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Grilled Salmon",
      description: "Marinated in basil, garlic, sea salt, and olive oil.",
      price: "25",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_8r7lr23ml-1631914417000",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 38,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 28,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_5rqtrrtgk",
      createdAt: "2021-09-17T21:06:26.140Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Kung Pao Shrimp",
      description:
        "Chili, onion, asparagus, zucchini, and peanuts. Hot and spicy.",
      price: "24.9",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_20jtw1icb-1631914376494",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 38,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 34,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_0isgd8erf",
      createdAt: "2021-09-17T21:06:27.306Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Lobster Garlic Noodles",
      description:
        "Maine lobster chopped in pieces , stirred in garlic and wine sauce, on top of Chinese egg noodles.",
      price: "39",
      photos: null,
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 39,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 36,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_smywy2oia",
      createdAt: "2021-09-17T21:06:26.941Z",
      updatedAt: "2022-09-01T08:32:34.250Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Baked Crab Hand Roll",
      description:
        "With spicy mayo wrapped with soy paper. All rolls include avocado and are wrapped in soy paper, unless otherwise specified. Hot and spicy.",
      price: "6",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_lsuzsx0gv-1631914956932",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 33,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 3,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_i9zfntgdj",
      createdAt: "2021-09-17T21:06:26.180Z",
      updatedAt: "2022-09-01T08:32:34.250Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Black Pepper Maine Lobster with garlic noodles",
      description: "Garlic, ginger, onion, black pepper, and butter.",
      price: "39",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_jnd9iyrhi-1631914769662",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 38,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 8,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_oezb574x0",
      createdAt: "2021-09-17T21:06:27.216Z",
      updatedAt: "2022-09-01T08:34:05.100Z",
      version: 6,
      merchantId: "b_9vbdnv0r1",
      name: "Black Pepper Lobster Noodle",
      description:
        "Maine lobster chopped in pieces , stirred in black pepper sauce on top of Chinese egg noodles. Hot and spicy.",
      price: "39",
      photos: [],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 47,
      categoryId: 39,
      inventory: {
        dailyCurrentStock: 0,
      },
      pointsToRedeem: null,
      displayOrder: 7,
      ingredientTags: {},
      badges: {},
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_3jfxbrg9n",
      createdAt: "2021-08-26T07:44:20.110Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 11,
      merchantId: "b_9vbdnv0r1",
      name: "Crispy Garlic Brussels Sprouts",
      description: "",
      price: "6.00",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_o1wvf3zto-1629963856523",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 4,
      inventory: {
        dailyMaxStock: null,
        dailyCurrentStock: 0,
      },
      pointsToRedeem: null,
      displayOrder: 17,
      ingredientTags: null,
      badges: null,
      rating: {
        rating: {
          taste: 5,
          value: 5,
          overall: 5,
          portion: 0,
        },
        ratingSum: {
          taste: 10,
          value: 10,
          overall: 10,
          portion: 0,
        },
        reviewCount: 2,
      },
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_2x1wibp73",
      createdAt: "2021-08-26T16:15:09.429Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 8,
      merchantId: "b_9vbdnv0r1",
      name: "Seaweed Salad",
      description: "",
      price: "7",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_4v86kf92h-1629994507910",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 9,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 57,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_cwl19kedq",
      createdAt: "2021-08-26T08:05:05.198Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 12,
      merchantId: "b_9vbdnv0r1",
      name: "The Monkey Brain",
      description:
        "Tempura, avocado stuffed with spicy tuna and crabmeat cupped with spicy eel sauce. Hot and spicy.",
      price: "11",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_p5m6bzh4x-1629965103946",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 4,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 78,
      ingredientTags: null,
      badges: null,
      rating: {
        rating: {
          taste: 5,
          value: 4,
          overall: 4,
          portion: 0,
        },
        ratingSum: {
          taste: 5,
          value: 4,
          overall: 4,
          portion: 0,
        },
        reviewCount: 1,
      },
      ranking: 0,
      unitsSold: 22,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_cnj8k5chc",
      createdAt: "2021-09-17T20:53:10.523Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 6,
      merchantId: "b_9vbdnv0r1",
      name: "Baked Salmon Roll",
      description: "Baked salmon on top of a California roll. Hot and spicy.",
      price: "15",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_mf8phcbwt-1631914565588",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 2,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 91,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_vt7ngo1l0",
      createdAt: "2021-09-17T20:53:10.248Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 6,
      merchantId: "b_9vbdnv0r1",
      name: "Black Dragon Roll",
      description: "California rolls topped with eel.",
      price: "15",
      photos: null,
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 2,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 92,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_g1s9mq9cl",
      createdAt: "2021-09-17T21:06:26.402Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 6,
      merchantId: "b_9vbdnv0r1",
      name: "California Roll",
      description: "Crab meat, asparagus, and avocado.",
      price: "9",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_u9dcydmaw-1631914687933",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 2,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 93,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_n42ejde7g",
      createdAt: "2021-09-17T21:06:26.741Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 6,
      merchantId: "b_9vbdnv0r1",
      name: "Crazy Roll",
      description: "Salmon, tuna, yellowtail, crabmeat, lettuce, ponzu.",
      price: "14",
      photos: null,
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 2,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 95,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_usgtmzhtk",
      createdAt: "2021-09-17T20:53:10.681Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 6,
      merchantId: "b_9vbdnv0r1",
      name: "Albacore Roll",
      description: "",
      price: "6",
      photos: null,
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 2,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 89,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_ce3o3ijea",
      createdAt: "2021-09-17T20:53:10.273Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 6,
      merchantId: "b_9vbdnv0r1",
      name: "Asparagus Roll",
      description: "",
      price: "6",
      photos: null,
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 2,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 90,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_2z24mck6y",
      createdAt: "2021-09-17T21:06:26.661Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 6,
      merchantId: "b_9vbdnv0r1",
      name: "Crunchy Roll",
      description:
        "Shrimp tempura, avocado, and cream cheese topped with tempura crunch and eel sauce.",
      price: "12",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_s49lzmp2y-1631914251198",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 2,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 96,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_jjgzf0rg9",
      createdAt: "2021-09-17T21:06:26.380Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 8,
      merchantId: "b_9vbdnv0r1",
      name: "Eel and Avocado Rolls",
      description: "Crab meat, asparagus, avocado, eel, sesame, and eel sauce.",
      price: "9",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_6xdrm0be9-1631914809979",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 2,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 97,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_5qtys9le9",
      createdAt: "2021-09-17T20:53:09.845Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Hot and Sour Soup",
      description: "With scallions.",
      price: "4",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_fz19l0nrm-1631914358311",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 3,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 31,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_hs01erp55",
      createdAt: "2021-09-17T20:53:09.800Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Jasmine White Rice",
      description: "",
      price: "2",
      photos: null,
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 35,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 32,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_9bzebilo0",
      createdAt: "2021-09-17T20:53:09.477Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Korean Style Short Ribs",
      description:
        "Sliced bone-in short ribs with Korean BBQ flavor. Serve with daily vegetables.",
      price: "24",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_0wjz3b4zn-1631914502937",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 63,
      categoryId: 36,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 33,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_z96xcd3sw",
      createdAt: "2021-09-17T20:53:10.041Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 6,
      merchantId: "b_9vbdnv0r1",
      name: "Honey Walnut Shrimp",
      description: "Crispy prawns with glazed honey walnuts.",
      price: "21",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_nqbnnor0q-1631915142420",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 75,
      categoryId: 38,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 29,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_dri0gr9c6",
      createdAt: "2021-09-17T20:53:09.619Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 6,
      merchantId: "b_9vbdnv0r1",
      name: "Lemon Chicken1",
      description:
        "Lightly breaded crispy chicken breast with fresh lemon sauce on the side.",
      price: "17",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_egtwadj90-1631914595612",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 72,
      categoryId: 37,
      inventory: {
        dailyCurrentStock: null,
      },
      pointsToRedeem: null,
      displayOrder: 35,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_n4vb5bk03",
      createdAt: "2021-09-17T20:53:10.886Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Ma La Chili Boiling Beef",
      description:
        "Slices of beef boiling in peppercorn chili garlic oil. Hot and spicy.",
      price: "20",
      photos: null,
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 40,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 37,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_p81m2yfc7",
      createdAt: "2021-09-17T20:53:10.330Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 6,
      merchantId: "b_9vbdnv0r1",
      name: "Green Dragon Roll",
      description:
        "Spicy tuna roll topped with avocado and spicy creamy sauce.",
      price: "15",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_ojmytho36-1631914912864",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 2,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 98,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_uwin1javl",
      createdAt: "2021-09-17T20:53:10.315Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 6,
      merchantId: "b_9vbdnv0r1",
      name: "Spicy Albacore Roll",
      description: "Spicy mayo and avocado.",
      price: "9",
      photos: null,
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 2,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 107,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_4yvtolxjk",
      createdAt: "2021-09-17T20:53:10.909Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Ma La Chili Boiling Fish Filet",
      description:
        "Fish filet boiling in peppercorn chili garlic oil. Hot and spicy.",
      price: "20",
      photos: null,
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 40,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 38,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_mr7z3xd4t",
      createdAt: "2021-09-17T20:53:10.148Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 7,
      merchantId: "b_9vbdnv0r1",
      name: "Ma Po Tofu",
      description: "Soft tofu in Szechuan-style spicy sauce. Hot and spicy.",
      price: "12",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_99lplczq4-1631914872793",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 41,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 39,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_rhn2m0nrf",
      createdAt: "2021-09-17T20:53:10.862Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Spicy Albacore Hand Roll",
      description: "Spicy",
      price: "6",
      photos: null,
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 33,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 63,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_1om9om1w7",
      createdAt: "2021-08-26T07:59:37.446Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 10,
      merchantId: "b_9vbdnv0r1",
      name: "Vegetable Tempura",
      description: "Sweet potato, string beans, eggplant, Japanese pumpkin.",
      price: "7.00",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_spd4viqps-1629964776236",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 4,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 84,
      ingredientTags: null,
      badges: null,
      rating: {
        rating: {
          taste: 4,
          value: 2.5,
          overall: 2.5,
          portion: 0,
        },
        ratingSum: {
          taste: 8,
          value: 5,
          overall: 5,
          portion: 0,
        },
        reviewCount: 2,
      },
      ranking: 0,
      unitsSold: 10,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_3xyjccgax",
      createdAt: "2021-09-17T20:53:09.993Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "White Fish Fillet with Asparagus",
      description: "Wok-tossed in a black bean sauce.",
      price: "18",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_5lzy503cp-1631914281088",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 61,
      categoryId: 38,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 85,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_1fs6qvupf",
      createdAt: "2021-09-17T20:53:09.861Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Wonton Soup",
      description:
        "Chicken and shrimp-stuffed wontons with rice chicken broth.",
      price: "6",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_nc6xddwv1-1631914194052",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 3,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 86,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_3vq6asdk9",
      createdAt: "2021-09-17T20:53:10.956Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Yellowtail",
      description: "Two piecses.",
      price: "7",
      photos: null,
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 54,
      categoryId: 32,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 87,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_o4k218bwx",
      createdAt: "2021-09-17T21:06:25.911Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Young Chow Fried Rice",
      description:
        "With shrimp, chicken, and beef. All fried rice entrée come with peas, carrots, scallions, & eggs.",
      price: "17",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_vi3a52dkt-1631914899003",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 45,
      categoryId: 35,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 88,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_4km2cgs55",
      createdAt: "2021-09-17T21:06:26.595Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 6,
      merchantId: "b_9vbdnv0r1",
      name: "Crab Meat and Salmon Rolls",
      description: "Crab meat, cream cheese, avocado, salmon, and eel sauce.",
      price: "15",
      photos: null,
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 2,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 94,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_Stuxr3lM",
      createdAt: "2022-09-02T09:45:14.746Z",
      updatedAt: "2022-09-02T09:45:14.746Z",
      version: 1,
      merchantId: "b_9vbdnv0r1",
      name: "item2",
      description: "",
      price: "331",
      photos: null,
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: null,
      inventory: {
        dailyCurrentStock: 0,
      },
      pointsToRedeem: null,
      displayOrder: 999999,
      ingredientTags: {},
      badges: {},
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "hour",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_y8pvwqguu",
      createdAt: "2021-09-17T21:06:26.580Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 6,
      merchantId: "b_9vbdnv0r1",
      name: "Shrimp Tempura Rolls",
      description: "Shrimp tempura, asparagus, and eel sauce.",
      price: "9",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_i9dxhi2nu-1631915112511",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 2,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 105,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_0zr3dbwcv",
      createdAt: "2021-09-17T21:06:26.460Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 6,
      merchantId: "b_9vbdnv0r1",
      name: "Smoky Sunset Roll",
      description:
        "Smoked salmon, cream cheese, & jalapeño deep fried in tempura with eel sauce. Hot and spicy.",
      price: "14",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_y5wv6b5jz-1631914119472",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 2,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 106,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_6n6f51477",
      createdAt: "2021-09-17T21:06:26.762Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 6,
      merchantId: "b_9vbdnv0r1",
      name: "Spicy Crabmeat Tempura Roll",
      description:
        "Crispy crab meat tempura roll topped with eel sauce, sriracha, and spicy mayo.",
      price: "13",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_z76om2s19-1631914430795",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 2,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 108,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_kc96yyrox",
      createdAt: "2021-09-17T20:53:10.544Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 8,
      merchantId: "b_9vbdnv0r1",
      name: "Spicy Tuna Roll",
      description: "Tuna and avocado. Hot and spicy.",
      price: "9",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_vpminiutz-1631914842086",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 2,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 109,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_hf93a97df",
      createdAt: "2021-09-17T20:53:11.279Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 4,
      merchantId: "b_9vbdnv0r1",
      name: "Chow Fun",
      description: "Flat rice noodles with bean sprouts and scallions.",
      price: "16",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_m40ytogi8-1631914743252",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 54,
      categoryId: 1,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 14,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_ao7s8vked",
      createdAt: "2021-09-17T21:06:25.958Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Crazy Fried Rice",
      description:
        "Fresh ginger, garlic, and egg whites. All fried rice entrée come with peas, carrots, scallions, & eggs.",
      price: "14",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_2z3al1621-1631914519091",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 57,
      categoryId: 35,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 16,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_oaci8m66g",
      createdAt: "2021-08-26T08:02:36.635Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 29,
      merchantId: "b_9vbdnv0r1",
      name: "Crispy Garlic Chicken Wings",
      description:
        "Six pieces. Garlic, green onions, jalapeños, pepper, and salt. Hot and spicy.",
      price: "11",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_zsvl433ez-1629964955157",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 4,
      inventory: null,
      pointsToRedeem: 1100,
      displayOrder: 18,
      ingredientTags: null,
      badges: null,
      rating: {
        rating: {
          taste: 4.5,
          value: 4,
          overall: 4.5,
          portion: 2,
        },
        ratingSum: {
          taste: 9,
          value: 8,
          overall: 9,
          portion: 4,
        },
        reviewCount: 2,
      },
      ranking: 0,
      unitsSold: 43,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_4b0mgwgxe",
      createdAt: "2021-09-17T20:53:09.521Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Emperor's Beef",
      description:
        "Lightly battered crispy thin slices of beef in a spicy plum sauce. Hot and spicy.",
      price: "18",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_j7tqnligm-1631914325015",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 36,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 23,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_wpkt5gxyc",
      createdAt: "2021-09-17T20:53:11.382Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Albacore & Crispy Onion in Garlic Ponzu Carpaccio",
      description: "Six pieces.",
      price: "14",
      photos: null,
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 31,
      inventory: {
        dailyMaxStock: null,
        dailyCurrentStock: 0,
      },
      pointsToRedeem: null,
      displayOrder: 1,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_yp446a2o1",
      createdAt: "2021-09-17T21:06:25.746Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 7,
      merchantId: "b_9vbdnv0r1",
      name: "Curry Chicken3",
      description:
        "Chicken breast, yellow curry, coconut milk, potatoes, carrots, celery, lemongrass, onions . Hot and spicy.",
      price: "17",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_htu00ia90-1631915128107",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 37,
      inventory: {
        dailyCurrentStock: null,
      },
      pointsToRedeem: null,
      displayOrder: 20,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_pitrlyl7a",
      createdAt: "2021-09-17T21:06:25.811Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Double Kung Pao",
      description:
        "Spicy chicken and shrimp sautéed with asparagus, zucchini, onions, and peanuts. Hot and spicy.",
      price: "18",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_f49y7obsz-1631914928340",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 66,
      categoryId: 37,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 21,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_nw8s7d28p",
      createdAt: "2021-09-17T21:06:26.039Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Shrimp Fried Rice",
      description:
        "All fried rice entrée come with peas, carrots, scallions, & eggs.",
      price: "17",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_nops1j7d1-1631914885517",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 71,
      categoryId: 35,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 60,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_cm224b6ip",
      createdAt: "2021-09-17T20:53:10.935Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Tuna",
      description: "Two pieces.",
      price: "7",
      photos: null,
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 41,
      categoryId: 32,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 80,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_uu4saufsy",
      createdAt: "2021-09-17T21:06:27.622Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Tuna Carpaccio",
      description: "Six pieces. Pickle wasabi, olive oil.",
      price: "15",
      photos: null,
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 31,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 81,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_5coas8lbr",
      createdAt: "2021-09-17T21:06:25.556Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Vegan Kung Pao Chicken",
      description:
        "Spicy vegan chicken with asparagus, zucchini, onions, and peanuts. Hot and spicy. Vegan.",
      price: "18",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_s67yxhbwa-1631914341204",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 77,
      categoryId: 42,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 82,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_rqds2oa7p",
      createdAt: "2021-09-17T20:53:09.333Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Vegan Spicy Garlic Chicken",
      description:
        "Spicy vegan chicken with broccoli and onion. Hot and spicy. Vegan.",
      price: "18",
      photos: null,
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 42,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 83,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_72vp39ane",
      createdAt: "2021-09-17T21:06:26.641Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 6,
      merchantId: "b_9vbdnv0r1",
      name: "Late Night Party Roll",
      description:
        "Spicy crab meat and avocado rolls topped with baked lobster, scallops, scallion in a creamy sauce.",
      price: "15",
      photos: null,
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 2,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 99,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_6hgbr35yx",
      createdAt: "2021-08-04T05:21:11.595Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 11,
      merchantId: "b_9vbdnv0r1",
      name: "Peacock Roll",
      description:
        "Tempura fried spicy tuna with soy paper and avocado topped with spicy mayo and eel sauce.",
      price: "12",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_5ou7gcnha-1628054468400",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 2,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 100,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_g8mbypcw0",
      createdAt: "2021-09-17T21:06:26.540Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 6,
      merchantId: "b_9vbdnv0r1",
      name: "Philadelphia Roll",
      description: "Smoked salmon, cream cheese, avocado.",
      price: "9",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_8r037o5ur-1631914700847",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 2,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 101,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_7y1s1qlkr",
      createdAt: "2021-09-17T21:06:26.618Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 6,
      merchantId: "b_9vbdnv0r1",
      name: "Rainbow Roll",
      description:
        "Crab meat, avocado, asparagus, tuna, salmon, snapper, albacore.",
      price: "15",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_vc3n8r6fn-1631914460196",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 2,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 102,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_j1hscmfu0",
      createdAt: "2021-09-17T20:53:10.357Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 6,
      merchantId: "b_9vbdnv0r1",
      name: "Red Dragon Roll",
      description: "Spicy tuna roll topped with tuna and tempura crunch.",
      price: "15",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_7hq0fb2mq-1631914795593",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 2,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 103,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_vc4rxuwbp",
      createdAt: "2021-09-17T21:06:26.721Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 8,
      merchantId: "b_9vbdnv0r1",
      name: "Spicy Yellowtail Roll",
      description: "Spicy, yellowtail and chopped scallions.",
      price: "11",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_iep1ogtya-1631915052328",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 2,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 110,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_ge2l5dbp1",
      createdAt: "2021-09-17T21:06:26.781Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 8,
      merchantId: "b_9vbdnv0r1",
      name: "Truffle Salmon Roll",
      description:
        "Spicy salmon rolls topped with salmon, white truffle oil, avocado, micro greens, and sea salt.",
      price: "17",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_pwnpfutlz-1631914714587",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 2,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 111,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_49izh6gwv",
      createdAt: "2021-09-17T21:06:26.800Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 8,
      merchantId: "b_9vbdnv0r1",
      name: "Volcano Roll",
      description:
        "Spicy crispy shrimp, tempura roll topped with eel and spicy sauce.",
      price: "15",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_bflbi6owu-1631914310495",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 2,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 112,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_vSDGzoOy",
      createdAt: "2022-09-01T08:23:02.315Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 2,
      merchantId: "b_9vbdnv0r1",
      name: "Training ",
      description: "sdffsfd",
      price: "0.08",
      photos: null,
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: null,
      inventory: {
        dailyCurrentStock: 0,
      },
      pointsToRedeem: null,
      displayOrder: 113,
      ingredientTags: {},
      badges: {},
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "minutes",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_oi9zzypzd",
      createdAt: "2021-08-04T07:07:25.473Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 17,
      merchantId: "b_9vbdnv0r1",
      name: "Edamame with Sea Salt",
      description: "",
      price: "5",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_rwv22e0dy-1628060842562",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 4,
      inventory: {
        lastSoldOut: "2022-05-30T10:06:27.506Z",
        dailyMaxStock: null,
        dailyCurrentStock: 0,
      },
      pointsToRedeem: null,
      displayOrder: 22,
      ingredientTags: null,
      badges: null,
      rating: {
        rating: {
          taste: 5,
          value: 5,
          overall: 5,
          portion: 0,
        },
        ratingSum: {
          taste: 5,
          value: 5,
          overall: 5,
          portion: 0,
        },
        reviewCount: 1,
      },
      ranking: 0,
      unitsSold: 10,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_fh06288y1",
      createdAt: "2021-09-17T21:06:25.662Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Garlic Black Bean Pork Belly",
      description:
        "Premium pork belly sauteed with garlic, bell peppers, jalapeno peppers, and ginger in a black bean sauce. Spicy.",
      price: "21.9",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_1bocnvo48-1631914655208",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 36,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 25,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_th9ewwnmt",
      createdAt: "2021-09-17T20:53:11.219Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 7,
      merchantId: "b_9vbdnv0r1",
      name: "Garlic Noodles with Lobster",
      description: "Lobster meat sautéed with Garlic noodles",
      price: "39",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_r7yb4ete6-1631914989524",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 1,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 26,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_y8cmsdfys",
      createdAt: "2021-09-17T20:53:10.128Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 6,
      merchantId: "b_9vbdnv0r1",
      name: "Spicy Garlic Eggplant",
      description: "Bell peppers and wood ear mushrooms. Hot and spicy.",
      price: "12",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_jz18tx48x-1631915097401",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 42,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 65,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_qf2p1cn0t",
      createdAt: "2021-09-17T20:53:11.239Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 7,
      merchantId: "b_9vbdnv0r1",
      name: "Garlic Noodles with Parmesan Cheese",
      description:
        "Garlic noodles with Parmesan cheese and green onions (you can add grilled chicken or grilled shrimp for an additional charge)",
      price: "11",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_fa3xklf77-1631914943232",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 44,
      categoryId: 1,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 27,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_gzes7l78e",
      createdAt: "2021-09-17T20:53:09.582Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Orange Crispy Chicken",
      description: "Hot and spicy.",
      price: "18",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_3oj78zr30-1631914728709",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 64,
      categoryId: 37,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 45,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_tm99qbmpd",
      createdAt: "2021-09-17T21:06:27.573Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 6,
      merchantId: "b_9vbdnv0r1",
      name: "Hamachi Carpaccio",
      description:
        "Six pieces. With scallions, jalapeños, garlic ponzu sauce. Hot and spicy.",
      price: "15",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_qnbbrf75o-1631915018661",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 31,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 30,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_ldpu7x1vb",
      createdAt: "2021-08-26T08:05:53.860Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 16,
      merchantId: "b_9vbdnv0r1",
      name: "Minced Chicken Lettuce Cups",
      description:
        "Four pieces. Wok-tossed minced chicken, jicama, and onions with hoisin sauce.",
      price: "11",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_99b5xvdot-1629965152404",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 4,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 41,
      ingredientTags: null,
      badges: null,
      rating: {
        rating: {
          taste: 5,
          value: 5,
          overall: 5,
          portion: 0,
        },
        ratingSum: {
          taste: 10,
          value: 10,
          overall: 10,
          portion: 0,
        },
        reviewCount: 2,
      },
      ranking: 0,
      unitsSold: 34,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_8d528k8mm",
      createdAt: "2021-08-26T16:20:38.685Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 6,
      merchantId: "b_9vbdnv0r1",
      name: "Mixed Sashimi Salad",
      description:
        "Assorted fresh sashimi, avocado, mixed greens, seaweed salad, and cucumbers with Japanese soy dressing.",
      price: "16",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_sf1qpck6b-1629994623530",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 9,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 43,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_k7q7jy1l6",
      createdAt: "2021-09-17T20:53:09.401Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Mongolian Beef",
      description:
        "Tender beef lightly stir-fried with scallions and fresh ginger. Hot and spicy.",
      price: "18",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_ceqavcnka-1631914823266",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 43,
      categoryId: 36,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 44,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_vd8wvbhxu",
      createdAt: "2021-09-17T21:06:27.527Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Pad Thai",
      description:
        "Thai glass noodles with chicken, shrimp, bean sprouts, onions, eggs, and ground peanuts. Hot and spicy.",
      price: "16",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_kxrmjc6f8-1631915065211",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 60,
      categoryId: 1,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 47,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_9zs9yoyk0",
      createdAt: "2021-09-17T20:53:11.432Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 7,
      merchantId: "b_9vbdnv0r1",
      name: "Pan-Fried Dumplings",
      description: "Six pieces.",
      price: "10",
      photos: null,
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 67,
      categoryId: 30,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 48,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_mo23v3r7a",
      createdAt: "2021-09-17T20:53:10.993Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Salmon",
      description: "Two pieces.",
      price: "6",
      photos: null,
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 68,
      categoryId: 32,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 49,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_sjfnwobcy",
      createdAt: "2021-09-17T20:53:10.751Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Salmon Skin Hand Roll",
      description: "",
      price: "7",
      photos: null,
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 33,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 50,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_7uxtatnc2",
      createdAt: "2021-09-17T21:06:27.241Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Salt and Pepper Crispy Lobster",
      description:
        "Crispy light batter, salt and pepper, jalapeno, onion. Hot and spicy",
      price: "39",
      photos: null,
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 51,
      categoryId: 39,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 51,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_lnlme3z14",
      createdAt: "2021-09-17T21:06:27.198Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Sampler",
      description:
        "Eight pieces. Two of each salmon, yellowtail, tuna and albacore.",
      price: "22",
      photos: null,
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 69,
      categoryId: 32,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 52,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_vlc4ocqz4",
      createdAt: "2021-09-17T21:06:27.353Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Sashimi Deluxe Dinner",
      description:
        "12 pieces (three salmon, three tuna, three yellowtail and three albacore). Served with Miso soup & house salad.",
      price: "29",
      photos: null,
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 34,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 53,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_17mza000e",
      createdAt: "2021-09-17T21:06:26.281Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Sauteed Fresh Mixed Vegetables",
      description:
        "Broccoli, Napa, Zucchini, Mushrooms, Asparagus, Garlic, Onions.",
      price: "12",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_jm10nzvxf-1631914147821",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 41,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 54,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_ihddm9hb9",
      createdAt: "2021-09-17T21:06:25.977Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 6,
      merchantId: "b_9vbdnv0r1",
      name: "Seafood Fried Rice",
      description:
        "Salmon, shrimp peas and carrots. All fried rice entrée come with peas, carrots, scallions, & eggs.",
      price: "17",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_fbirtzsn5-1631914782489",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 58,
      categoryId: 35,
      inventory: {
        dailyCurrentStock: 0,
      },
      pointsToRedeem: null,
      displayOrder: 55,
      ingredientTags: {},
      badges: {},
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_6nzi731si",
      createdAt: "2021-09-17T21:06:27.261Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Seafood Pan Fried Noodles",
      description:
        "Fish filet, shrimp, squid, with white wine sauce on top of pan fried noodles.",
      price: "18",
      photos: null,
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 52,
      categoryId: 39,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 56,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_zlexxfexh",
      createdAt: "2021-09-17T21:06:27.505Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Shanghai Lo Mein",
      description: "With bean sprouts, scallions, cabbage, and carrots.",
      price: "16",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_52hh463l0-1631915172468",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 56,
      categoryId: 1,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 58,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_nhxudlxee",
      createdAt: "2021-08-26T07:45:10.440Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 15,
      merchantId: "b_9vbdnv0r1",
      name: "Shishito Peppers in Soy Sauce",
      description: "Hot and spicy",
      price: "6.00",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_jb15sm27z-1629963909010",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 4,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 59,
      ingredientTags: null,
      badges: null,
      rating: {
        rating: {
          taste: 5,
          value: 5,
          overall: 4,
          portion: 0,
        },
        ratingSum: {
          taste: 5,
          value: 5,
          overall: 4,
          portion: 0,
        },
        reviewCount: 1,
      },
      ranking: 0,
      unitsSold: 29,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_czl7e2h5u",
      createdAt: "2021-09-17T20:53:10.089Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Shrimp with Asparagus",
      description: "Wok-tossed in a white wine sauce.",
      price: "18",
      photos: null,
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 76,
      categoryId: 38,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 61,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_3y9mml271",
      createdAt: "2021-09-17T21:06:27.461Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 7,
      merchantId: "b_9vbdnv0r1",
      name: "Singapore-Style Noodles",
      description:
        "Curry-flavored thin rice noodles wok-tossed with chicken, shrimp, red bell peppers, bean sprouts, onions, and egg.",
      price: "16",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_6hqilngaj-1631914295179",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 48,
      categoryId: 1,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 62,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_dr9nxv0hz",
      createdAt: "2021-09-17T20:53:09.556Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Spicy Garlic Chicken with Broccoli",
      description:
        "Chicken breast and ground garlic wok-tossed with broccoli. Hot and spicy.",
      price: "17",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_3jq6z9kjy-1631914580375",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 59,
      categoryId: 37,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 64,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_9biizeudb",
      createdAt: "2021-09-17T21:06:26.221Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Spicy Garlic Shrimp",
      description:
        "Shrimp and ground garlic wok-tossed with broccoli, onions, ginger, and spicy soy sauce. Hot and spicy.",
      price: "18",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_5rnflqpsx-1631914489536",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 74,
      categoryId: 38,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 66,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_75etwwjgc",
      createdAt: "2021-09-17T21:06:27.375Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Spicy Maki Combination Dinner",
      description:
        "One each of spicy tuna rolls, spicy California rolls, spicy salmon rolls. Served with Miso soup and house salad.",
      price: "22",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_gstj81g1h-1631914443919",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 55,
      categoryId: 34,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 68,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_fcgm3gy4e",
      createdAt: "2021-09-17T21:06:26.879Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Spicy Salmon Hand Roll",
      description:
        "Hot and spicy. All rolls include avocado and are wrapped in soy paper, unless otherwise specified.",
      price: "6",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_vqh8pv1c0-1631914639429",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 33,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 69,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_mluqo6mf6",
      createdAt: "2021-09-17T20:53:10.706Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Spicy Scallop Hand Roll",
      description: "Hot and spicy.",
      price: "7",
      photos: null,
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 33,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 70,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_3vxqurbbj",
      createdAt: "2021-09-17T21:06:26.961Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Spicy Tuna Hand Roll",
      description:
        "Hot and spicy. All rolls include avocado and are wrapped in soy paper, unless otherwise specified.",
      price: "6",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_qfsvhc9op-1631914266363",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 33,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 71,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_jumavxjhw",
      createdAt: "2021-08-26T08:08:45.182Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 13,
      merchantId: "b_9vbdnv0r1",
      name: "Spicy Tuna on Crispy Rice",
      description:
        "Six pieces. Spicy tuna (served cold) on rice cake with avocado, onion, jalapenos, mayo & eel sauce.",
      price: "13",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_lz69c317x-1629965323242",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 4,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 72,
      ingredientTags: null,
      badges: null,
      rating: {
        rating: {
          taste: 5,
          value: 5,
          overall: 5,
          portion: 0,
        },
        ratingSum: {
          taste: 5,
          value: 5,
          overall: 5,
          portion: 0,
        },
        reviewCount: 1,
      },
      ranking: 0,
      unitsSold: 7,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_zjnumknvh",
      createdAt: "2021-09-17T21:06:26.994Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Spicy Yellowtail Hand Roll",
      description:
        "With scallions. Hot and spicy. All rolls include avocado and are wrapped in soy paper, unless otherwise specified.",
      price: "6",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_c8ntff5cz-1631915157712",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 33,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 73,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_2bh891nez",
      createdAt: "2021-09-17T21:06:27.333Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Steamed Spicy Whole Fish",
      description:
        "Whole Branzino topped with ground chili and garlic, steamed with soy sauce. Hot and spicy.",
      price: "35",
      photos: null,
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 39,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 74,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_96epv5bmd",
      createdAt: "2021-09-17T21:06:25.614Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Sweet Sour Pork",
      description:
        "Crispy chunks of premium pork belly with bell peppers, onions, and pineapple in sweet and sour sauce.",
      price: "17",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_no00leskb-1631914476055",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 46,
      categoryId: 36,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 76,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_2jo1d8yli",
      createdAt: "2021-09-17T20:53:09.639Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 7,
      merchantId: "b_9vbdnv0r1",
      name: "Teriyaki Chicken",
      description: "Grilled chicken breast topped with teriyaki sauce.",
      price: "19",
      photos: [
        "https://bos-merchant-images.s3-us-west-1.amazonaws.com/image-p_hjypgtleq-1631914234116",
      ],
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: 73,
      categoryId: 37,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 77,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
    {
      id: "m_z0ipfnrl2",
      createdAt: "2021-09-17T21:06:27.551Z",
      updatedAt: "2022-09-01T08:32:06.206Z",
      version: 5,
      merchantId: "b_9vbdnv0r1",
      name: "Truffle Salmon Carpaccio",
      description: "Six pieces. Pickle, wasabi, olive oil.",
      price: "14",
      photos: null,
      videos: null,
      visible: true,
      featured: false,
      modifierTemplateId: null,
      categoryId: 31,
      inventory: null,
      pointsToRedeem: null,
      displayOrder: 79,
      ingredientTags: null,
      badges: null,
      rating: null,
      ranking: 0,
      unitsSold: 0,
      unit: "default",
      unitQuantity: 1,
      noCoupons: false,
    },
  ],
};
